<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>SolutionComponentCloner</RootNamespace>
    <AssemblyName>SolutionComponentCloner</AssemblyName>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Deterministic>true</Deterministic>
    <Platforms>AnyCPU</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Configuration" />
    <Reference Include="System.ComponentModel.Composition" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="XrmToolBoxPackage" Version="1.2025.10.74" />
    <PackageReference Include="MscrmTools.Xrm.Connection" Version="1.2025.9.64" />
  </ItemGroup>

</Project>
